# Generated by Django 6.0.5 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('power_watts', models.FloatField()),
                ('energy_wh', models.FloatField()),
                ('period_minutes', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('endpoint_id', models.PositiveIntegerField(db_index=True)),
                ('protocol', models.CharField(max_length=16)),
                ('endpoint_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consumption', models.PositiveBigIntegerField()),
                ('tamper', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint_id', 'timestamp'], name='api_meterre_endpoin_2c0cac_idx')],
            },
        ),
    ]
